---
- hosts: all
  # CHANGEME: change this tasks and roles with code you want to test.
  #sudo: true
  pre_tasks:
  - name: run ansible galaxy
    local_action: command ansible-galaxy install -r requirements.yml
    become: false

  roles:
    - role: ansible-role-omd
      omd_site: omd_site_name
